.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

Les actions GitHubs se lançaient systématiquement à chaque push. Cela demande des ressources inutilement exploitées.
Mettre la directive d'exécution à pull-request uniquement.
Si on a:
```yml
on:
push:
pull_request
```
Cela exécute l'action sur les pushes et pull requests.

[BUGFIX] Corriger le lancement de la CI

---

locales/en.json
locales/fr.json
locales/it.json
src/settings.js
src/views/SettingsView.vue

Jusqu'à présent, on avait pas toutes les préférences en raison du déploiement progressif du site.
Ajouter le reste des préférences en mettant en place le même système que pour les paramètres précédents.
La connexion avec Eole ne peut pas être incluse de notre côté en raison du cryptage..

[FEATURE] Ajouter le reste des préférences

---

locales/en.json
locales/fr.json
locales/it.json
src/views/SettingsView.vue

Lorsqu'on se rendait sur la page, on devait forcément ouvrir un fichier existant pour pouvoir le modifier.
Ajouter un bouton permettant d'avoir le modèle avec les paramètres par défaut.

[FEATURE] Ajouter un bouton pour avoir le modèle par défaut

---

src/settings.js

Par défaut, la valeur d'avance de l'afficheur n'apparaissait pas dans la page.
Elle n'était pas présente, a été rajouté. Fixes #29

[BUGFIX] Ajouter la valeur par défaut pour l'avance de l'afficheur

---

locales/en.json
locales/fr.json
locales/it.json

strong html tags do not pass through translation files.
Write B.NOTE rather than B.note.

[BUGFIX] Remove <strong> in translation files

---

Contribution guide.md
src/__tests__/translations.test.js

There was no way to ensure that the site was fully translated into all supported languages.
Add a test that will verify that all languages are equal in terms of translation keys.
This can be a problem for some foreign pr.
Check that the CI passes correctly.

[TECH] Add a test for translations

---

.github/workflows/Update packages.yml
.github/workflows/Update version on merge.yml

If the code is formatted at the same time as the version mount, the git commit --amend deletes the tag associated with the commit.
Move the code formatting action in the workflow to update the project dependencies.
Is there a need to format?

[TECH] Format code when updating dependencies

---

locales/en.json
locales/fr.json
locales/it.json
src/views/DownloadPageView.vue

I had commented on part of the download page because I no longer wanted my releases to be visible. However, B.note updates are again in progress and therefore downloadable on the GitHub releases page.
Uncomment the lines of the template part and add a link to see all the releases.

[MINORFEATURE]

---

package.json

When we did `npm run lint` the linting corrected the necessary files but did not return errors if there were problems.
Add a command that checks files without modifying them.

[TECH] Add an order to not fix the linting

---

locales/en.json
locales/fr.json
locales/it.json
package-lock.json
package.json
src/router/router-list.js
src/views/AboutView.vue

There was no page about it with information on the development of the site or how to make reports or suggestions.
Add an about page with the following information:
- A brief history of the site,
- A link to the GitHub repository,
- Links to issue templates for features and bugs.
This information is subject to change.
Verify that a new about page is present on the site.

[MAJORFEATURE] Add an about page to the site

---

locales/en.json
locales/fr.json
locales/it.json
src/views/SettingsView.vue

In the settings management page, the message regarding the download issue was not translated during the internationalization of the site.
Add this message in the translations and replace the hard message in the code with the appropriate key.
- Go to the settings management page,
- Display the default model,
- Check that in each language, when you click on the `download` button, the confirmation message is displayed in the correct language.

[BUGFIX] Translate a forgotten message

---

.github/workflows/codeql.yml

The CodeQL workflow only started on pull requests or on the main branch.
Launch the workflow on each branch at a push.

[TECH] Launch the CodeQL workflow with each push

---

src/views/DownloadPageView.vue

On the download page, the latest available version was displayed, regardless of whether it was prereleased or not. However, we cannot offer prerelease versions on the site.
Add a loop that does a check.
- Go to the download page,
- Note that the proposed version is not a pre-version.

[BUGFIX] Proposer les versions définitive uniquement au téléchargement

---

src/__tests__/components/FooterComponent.spec.js
src/__tests__/components/LanguageComponent.spec.js
src/__tests__/components/NaveBarreComponent.spec.js
src/__tests__/components/SettingComponent.spec.js
src/__tests__/components/UploadFileComponent.spec.js
src/__tests__/helpers.js

- **feat: Add helper for tests**
- **fix: Rewrite tests with helper**
In tests, it must necessary to mock $t for all components. It was longer and repeat same instruction most times.
Create a helper file that render component with $t mocks automatically.
It's ok for this tests, bud for future acceptance tests?
Check that all tests pass.

[TECH] Rewrite tests with helper

---

src/App.vue

At the entry point of the site, the content of the page was placed in a simple div, which was not convenient for screen readers.
Place the view content in a main tag.
This has no impact on the tests.
On pages, check that the content is in a main tag

[MINORFEATURE] Place the content of the page in a main tag

---

package.json

The command publish is allready used by npm.
Use this command:
```shell
npm run production
```
You can't test this changes.

[BUGFIX] Change the name of action to publish a new version

---

.github/workflows/Merge into production.yml

THe github workflow doesn't accept the commande:
```shell
git merge main
```
Use this commande:
```shell
git merge origin/main
```

[BUGFIX] Correct the command to merge main into production

---

.github/workflows/Build version.yml

This pull request introduces a new GitHub Actions workflow to automate the process of generating and pushing a new version to the main branch. The workflow is designed to be run manually. Below are the key changes:
New GitHub Actions workflow:
* [`.github/workflows/Build version.yml`](diffhunk://#diff-22a4f6633866c296cdc85f184e7dc749986576390f3d72b4b9752c855d610e73R1-R39): Added a new workflow named "Build version" that runs manually to generate a new version and push it to the main branch. The workflow includes steps for checking out the repository, setting up Node.js, configuring git, installing dependencies, building the new version, and pushing it to the main branch.

[TECH] Put the workflow back to generate a new version

---

.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

This pull request includes changes to the GitHub Actions workflows to ensure that certain jobs only run when the pull request is not in draft mode.
Changes to GitHub Actions workflows:
* [`.github/workflows/check-lint.yml`](diffhunk://#diff-20fe1266f89be6c7574eb75d9d5f94a20068c4d38bc7ea1900074a6a69f7a917R10): Added a condition to the `eslint` job to run only if the pull request is not a draft.
* [`.github/workflows/check-tests.yml`](diffhunk://#diff-e6ca5345641700b84db3333c2e2038a963319137c37cf92fa6c3e214ccb8ede3R10): Added a condition to the `vitest` job to run only if the pull request is not a draft.

[TECH] Launch the CI only if the pull request is not in draft

---

.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

This pull request includes changes to the GitHub Actions workflows to trigger jobs only when a pull request is marked as ready for review. The most important changes include updating the `check-lint.yml` and `check-tests.yml` workflows.
Changes to GitHub Actions workflows:
* [`.github/workflows/check-lint.yml`](diffhunk://#diff-20fe1266f89be6c7574eb75d9d5f94a20068c4d38bc7ea1900074a6a69f7a917R7-L10): Added `types: ready_for_review` to trigger the lint job only when the pull request is ready for review and removed the draft check condition.
* [`.github/workflows/check-tests.yml`](diffhunk://#diff-e6ca5345641700b84db3333c2e2038a963319137c37cf92fa6c3e214ccb8ede3R7-L10): Added `types: ready_for_review` to trigger the test job only when the pull request is ready for review and removed the draft …

[TECH] Correct the syntax to launch the CI on the pr that are ready for review

---

.husky/pre-commit
package-lock.json
package.json

This pull request includes changes to add Husky for managing Git hooks and updates to the `package.json` file to include Husky as a dependency and configure it for pre-commit hooks.
* [`.husky/pre-commit`](diffhunk://#diff-d2bc4bbf14eadc292d84e0ef5f7a93115c23557f533809fc80b896934291529dR1-R2): Added commands to run tests and linting before each commit.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R39): Added `husky` as a dependency.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L17-R17): Added `prepare` script to set up Husky.

[TECH] Add a commit linting

---

package-lock.json
package.json
postcss.config.js

This pull request includes updates to dependencies and minor formatting changes in the `package.json` file. The most important changes include adding a new dependency, updating existing dependencies, and modifying the `postcss.config.js` file.
Dependency updates:
* Added `@tailwindcss/postcss` to the `devDependencies` in `package.json`.
* Updated the `postcss` dependency to version `8.5.1` in `package.json`.
* Updated the `tailwindcss` dependency to version `3.4.17` in `package.json`.
Configuration changes:
* Modified `postcss.config.js` to use `@tailwindcss/postcss` instead of `tailwindcss`.
Formatting changes:
* Reformatted the `TECH` and `BUMP` sections in `package.json` for better readability.

[BUMP] Update tailwindcss to use @tailwindcss/postcss

---

.github/dependabot.yml
.husky/pre-commit
package.json

This pull request includes several changes to configuration files and scripts to improve consistency and streamline processes. The most important changes involve updating labels and commit message prefixes in the Dependabot configuration, modifying the pre-commit script, and adjusting the section types in the `package.json` file.
Changes to Dependabot configuration:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R10-R19): Added `dependencies` and `npm` labels, and changed `prefix-development` from `chore` to `bump` for one update block.
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R28-R37): Added `dependencies` and `workflow` labels, and changed …

[BUGFIX] fix commit names and dependabot alert

---

.github/workflows/build-version.yml
.github/workflows/check-tests.yml

This pull request includes updates to the GitHub workflow configurations to enhance the testing and linting processes and to conditionally run certain jobs based on pull request labels.
Enhancements to testing and linting:
* [`.github/workflows/build-version.yml`](diffhunk://#diff-c8e0932e362c6cf2133d2797ec3edf7699d897d626a9f35f5e156ddc27636516R34-R38): Added steps to run tests and lint the code before building a new version.
Conditional job execution:
* [`.github/workflows/check-tests.yml`](diffhunk://#diff-e6ca5345641700b84db3333c2e2038a963319137c37cf92fa6c3e214ccb8ede3R10): Added a condition to skip the `vitest` job if the pull request contains the 'No deployment' label.

[FEATURE] Do not run tests if the "No deployment" label is present

---

.github/workflows/enable auto merge.yml

This pull request includes updates to the `.github/workflows/enable auto merge.yml` file to enhance the auto-merge functionality for pull requests. The most important changes include updating the event types that trigger the workflow, modifying job and step names for consistency, and refining the auto-merge conditions.
Workflow improvements:
* Added `opened` and `reopened` event types to trigger the workflow on pull requests.
* Changed job and step names to use consistent casing (`enable_auto_merge`).
* Updated the condition to enable auto-merge only if the pull request is labeled "Ready to merge" and is not a draft.
* Added a step to checkout the repository before enabling auto-merge.
* Refined the script to use the `@actions/github` library for enabling auto-merge.

[BUGFIX] Correct the workflow to enable auto merge

---

.github/dependabot.yml
.github/workflows/PR Title Check.yml

This pull request includes updates to the `.github/dependabot.yml` and `.github/workflows/PR Title Check.yml` files to improve the dependency management and pull request title validation process.
Improvements to dependency management:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R13-R19): Added the "Ready to merge" label to the `updates:` section for both npm and `github-actions` packages. Updated the commit message prefix from "bump" to "[BUMP]". [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R13-R19) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R32-R38)
Enhancements to pull request validation:
* [`.github/workflows/PR Title …

[BUGFIX] Add label ready to merge to Dependabot file

---

.github/dependabot.yml

This pull request includes changes to the `.github/dependabot.yml` file to update the assignee and commit message prefix for dependency updates.
Changes in `.github/dependabot.yml`:
* Updated the assignee from `theotime2005` to `dependabot` for dependency updates. [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L17-R19) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L36-R38)
* Modified the commit message prefix to include double quotes around `[BUMP]`. [[1]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L17-R19) [[2]](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L36-R38)

[BUGFIX] Fix Dependabot commit messages

---

locales/en.json
locales/fr.json
locales/it.json
src/__tests__/acceptance/SettingsView.spec.js
src/views/SettingsView.vue

This pull request includes updates to localization files and improvements to the `SettingsView` component and its tests. The most important changes include adding a new confirmation message for resetting configurations and enhancing the test coverage for the `SettingsView` component.
Localization updates:
* [`locales/en.json`](diffhunk://#diff-c9218bed23f0aeb93d7e1a7d5f6e1345fae20f4b8692b27fb97fd0f37b3d26d7L165-R166): Added a new confirmation message for resetting configurations.
* [`locales/fr.json`](diffhunk://#diff-86d23a5be9d54f3c756b91e0d6412ac8bbbb232600ab2ee5554ca46079b4f1e6L176-R177): Added a new confirmation message for resetting configurations.
* [`locales/it.json`](diffhunk://#diff-857654eba54a2149d43ab51b00c1daf863edc718308286e32a96cad8dc79342cL172-R173): Added a new …

[BUGFIX] Put a translation string in the settings management page

---

.github/workflows/enable auto merge.yml

This pull request includes a small change to the `.github/workflows/enable auto merge.yml` file. The change adds permissions for `pull-requests` and `contents` to the workflow configuration.
* [`.github/workflows/enable auto merge.yml`](diffhunk://#diff-39a04bab1c94543645918dfaeae11f004c72e1c6546ac2ad9a1d000aba25d5a9R7-R10): Added `permissions` section with `pull-requests: write` and `contents: read` to the workflow configuration.

[BUGFIX] Grant write access to a pull request

---

.github/workflows/enable auto merge.yml

This pull request includes a change to the `.github/workflows/enable auto merge.yml` file to enhance the security of the GitHub Actions workflow by using different tokens based on the actor.
Security enhancement:
* [`.github/workflows/enable auto merge.yml`](diffhunk://#diff-39a04bab1c94543645918dfaeae11f004c72e1c6546ac2ad9a1d000aba25d5a9L22-R22): Modified the `github-token` to use `secrets.DEPENDABOT_TOKEN` if the actor is `dependabot[bot]`, otherwise it uses `secrets.GH_TOKEN`.

[TECH] Use a special token for Dependabot

---

.github/workflows/build-version.yml

This pull request includes changes to the `.github/workflows/build-version.yml` file to enhance the build version workflow by adding input validation and allowing different types of releases. The most important changes are summarized below:
Enhancements to build version workflow:
* Added `release_type` input to allow specifying the type of release to generate.
* Included a validation step to ensure the `release_type` input is either 'major', 'minor', or 'patch'.
* Modified the build step to use the specified `release_type` for generating the new version.

[TECH] Add an input in the workflow to generate a version

---

.github/workflows/build-version.yml

This pull request includes a small change to the `.github/workflows/build-version.yml` file. The change corrects a typo in the `workflow_dispatch` event configuration by renaming `input` to `inputs`.

[BUGFIX] Add a s to inputs

---

src/__tests__/components/UploadFileComponent.spec.js
src/__tests__/stores/settingsStore.spec.js
src/components/UploadFileComponent.vue
src/stores/settingsStore.js
src/views/SettingsView.vue

This pull request includes updates to the `settingsStore` to track the file name associated with the settings and ensures proper event handling for the window before unload event. The most important changes include modifications to the store's state and actions, updates to the test cases, and adjustments to the `SettingsView` component.
* [`src/stores/settingsStore.js`](diffhunk://#diff-62cd24f59f77bffd672d5c4b07f77efb90866b3d9b90da00816c14bab1b1858aR6-R11): Added `fileName` to the state and modified the `loadSettings` and `removeAll` actions to handle the `fileName`. Added a `getFileName` getter. [[1]](diffhunk://#diff-62cd24f59f77bffd672d5c4b07f77efb90866b3d9b90da00816c14bab1b1858aR6-R11) [[2]](diffhunk://#diff-62cd24f59f77bffd672d5c4b07f77efb90866b3d9b90da00816c14bab1b1858aR21) …

[FEATURE] Keep the data on the settings page and display a warning if the user wants to leave the page without having saved

---

.github/workflows/comment-close-pull-request.yml
.github/workflows/comment-open-pull-request.yml

This pull request introduces two new GitHub workflows to automate commenting on pull requests when they are opened and closed. These workflows aim to improve communication with contributors by providing timely feedback and instructions.
New GitHub workflows:
* [`.github/workflows/comment-close-pull-request.yml`](diffhunk://#diff-a0c6b80b0c8ddbec312a22c33b55ec4359cab6e9891e9c519387d23c99a1e0f6R1-R15): Adds a workflow to comment on a pull request when it is merged, thanking the contributor and informing them about the feature deployment.
* [`.github/workflows/comment-open-pull-request.yaml`](diffhunk://#diff-49d44f98e2ee5868e602e6e156d6a2b1240ed63947f022457ee9ae36f5e6d2fbR1-R20): Adds a workflow to comment on a pull request when it is opened, guiding the contributor to follow the …

[TECH] Add workflow to comment pull requests

---

src/App.vue
src/components/FooterComponent.vue
src/components/LanguageComponent.vue
src/components/SettingComponent.vue
src/components/UploadFileComponent.vue
src/views/AboutView.vue
src/views/DownloadPageView.vue
src/views/FaqView.vue
src/views/HomeView.vue
src/views/SettingsView.vue

This pull request includes changes to improve accessibility and clean up unused styles in the codebase. The most important changes include adding a screen reader-only class to the skip content button and removing unnecessary scoped styles from several components and views.
Accessibility improvement:
* [`src/App.vue`](diffhunk://#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0L18-R18): Added a `class="sr-only"` to the skip content button to make it more accessible for screen readers.
Code cleanup:
* [`src/components/FooterComponent.vue`](diffhunk://#diff-7490b18034c0e87a348ce68c97884563c04d5fbe2ff5f42a85dc927ff0ce5f94L28-L31): Removed unused scoped styles.
* [`src/components/LanguageComponent.vue`](diffhunk://#diff-e4549888235201835af39686be6a12f253ad3cf5a47d20d5040a6e …

[BUGFIX] Remove unnecessary sections of style and stylize the button at the top of the page

---

package.json

This pull request includes a small change to the `package.json` file. The change removes the custom configuration for `standard-version` which defined sections for different commit types.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L19-L58): Removed the `standard-version` configuration that specified sections for commit types like "Features", "Bug Fixes", "Chores", etc.

[TECH] Remove unused scopes in standard version

---

src/App.vue
src/components/NavBarComponent.vue

This pull request includes changes to the `src/App.vue` and `src/components/NavBarComponent.vue` files to improve navigation accessibility and behavior. The most important changes include adding an event listener for cursor movement and updating the visibility of navigation elements based on screen size.
Improvements to navigation accessibility:
* [`src/App.vue`](diffhunk://#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0L19-R19): Added the `@move-cursor` event listener to the `NavBarComponent` to focus the main content when navigation occurs.
Updates to navigation behavior:
* [`src/components/NavBarComponent.vue`](diffhunk://#diff-a7a38de5ec74651b5cfb7131c9e7be7823db58565d6f459a9dd7ea2903c022ebR20-R31): Modified the `handleResize` method to update the visibility of …

[BUGFIX] Fermer la barre de navigation lorsqu'on clique dessus et amener le curseur sur le contenu de la page lorsqu'on clique sur un lien

---

sample.env

This pull request includes a small change to the `sample.env` file. The change adds a new configuration option to enable or disable the use of components with the composition API.
* [`sample.env`](diffhunk://#diff-b80385df109d2e96812772e7905b6d846a851623b7261d35480bdb4e83a009d0R14-R18): Added a new boolean configuration option `FT_ENABLE_COMPOSITION_API` with a default value of `false`.

[TECH] Add a feature toggle for switching to api composition

---

package.json
src/App.vue
src/__tests__/scripts/useLocaleCookie.spec.js
src/components/LanguageComponent.vue
src/scripts/useLocaleCookie.js

This pull request introduces the use of cookies to manage locale settings and updates several components and tests accordingly. The most important changes include adding a new dependency, updating the main application component, creating a new utility script, and modifying tests and other components to use this new functionality.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R23): Added `js-cookie` dependency to manage cookies.
* [`src/App.vue`](diffhunk://#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0L2-R8): Imported `useI18n` and `useLocaleCookie`, and added a function to set the locale from a cookie on mount. [[1]](diffhunk://#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0L2-R8) …

[FEATURE] Add a cookie to save the language on the site

---

.github/workflows/build-version.yml

This pull request includes a small change to the `.github/workflows/build-version.yml` file. The change sets the `fetch-depth` parameter to `0` in the `actions/checkout@v4` step to ensure the full repository history is fetched.

[BUGFIX] Fix the workflow for version build

---

.github/workflows/auto-merge.yml
package.json

This pull request includes changes to the GitHub Actions workflow configuration and the `package.json` file. The most important changes involve updating the workflow triggers and modifying the versioning configuration to use more descriptive labels.
Workflow configuration changes:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L11-R11): Replaced `check_suite` trigger with `ready_for_review` trigger to streamline the workflow events.
Versioning configuration changes:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L21-R50): Updated the `standard-version` configuration to use more descriptive labels for different types of changes, such as `[FEATURE]`, `[BUGFIX]`, and …

[TECH] Refactor the ci and the auto merge action

---

.github/workflows/auto-merge.yml
package.json

This pull request includes changes to streamline the auto-merge process in the GitHub workflow and to standardize the commit message types in the `package.json` file.
Changes to GitHub workflow:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L41-R41): Simplified the auto-merge command by removing the pull request number and title parameters from the `gh pr merge` command.
Standardization of commit message types:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L21-L58): Updated the commit message types to use conventional commit types (e.g., `feat`, `fix`, `chore`, etc.) and removed the `[TECH]` type.

[TECH] Restore the old configuration of standard version

---

.github/workflows/auto-merge.yml
.versionrc.json
eslint.config.mjs
package.json

This pull request includes several changes aimed at improving the release process and configuration management. The most important changes include replacing `standard-version` with `commit-and-tag-version`, updating the `.versionrc.json` file, and modifying the GitHub Actions workflow for auto-merging pull requests.
Release process improvements:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L15-L61): Replaced `standard-version` with `commit-and-tag-version` for the release process. [[1]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L15-L61) [[2]](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R36-L87)
* [`.versionrc.json`](diffhunk://#diff-fc8675bd9292cdcdca740165c0b6 …

[TECH] Switch to commit and tag

---

.github/workflows/build-version.yml

This pull request includes changes to the `.github/workflows/build-version.yml` file to simplify the build version workflow by removing the input validation and the release type input.
Simplifications to build version workflow:
* [`.github/workflows/build-version.yml`](diffhunk://#diff-c8e0932e362c6cf2133d2797ec3edf7699d897d626a9f35f5e156ddc27636516L8-L12): Removed the `inputs` section and its associated `release_type` input.
* [`.github/workflows/build-version.yml`](diffhunk://#diff-c8e0932e362c6cf2133d2797ec3edf7699d897d626a9f35f5e156ddc27636516L22-L28): Removed the step that checks if the `release_type` input is valid.
* [`.github/workflows/build-version.yml`](diffhunk://#diff-c8e0932e362c6cf2133d2797ec3edf7699d897d626a9f35f5e156ddc27636516L53-R41): Modified the `Build new version` …

[TECH] Configure the release workflow for semantic version

---

.github/workflows/auto-merge.yml

This pull request includes a change to the GitHub Actions workflow configuration in the `.github/workflows/auto-merge.yml` file. The most important change is the addition of branch and check suite triggers to the workflow.
Workflow configuration changes:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243R12-R18): Added branch trigger for `main` and check suite trigger for completed checks with a status of success.

[TECH] Add the check status to workflow to auto merge

---

src/components/LanguageComponent.vue
src/components/SettingComponent.vue
src/components/UploadFileComponent.vue
src/style.css
src/views/SettingsView.vue

This pull request focuses on enhancing the consistency and readability of the UI components by introducing custom CSS classes and resetting global styles. The changes span across multiple Vue components and the main stylesheet.
* [`src/components/LanguageComponent.vue`](diffhunk://#diff-e4549888235201835af39686be6a12f253ad3cf5a47d20d5040a6e2d90779e43L26-R26): Added the `custom-select` class to the language dropdown for consistent styling.
* [`src/components/SettingComponent.vue`](diffhunk://#diff-4b510c76d34984739ba35e177e172004533c9000a381ecd3963ab3b20b28b851L59-R59): Applied the `custom-input` and `custom-button` classes to various input elements and buttons to standardize their appearance. [[1]](diffhunk://#diff-4b510c76d34984739ba35e177e172004533c9000a381ecd3963ab3b20b28b851L59-R59) …

[BUGFIX] Customize the style of components

---

.github/dependabot.yml

This pull request includes changes to the `.github/dependabot.yml` file. The changes focus on modifying the labels and removing the assignees for Dependabot updates.
Key changes:
* Removed the `assignees` section, which previously assigned Dependabot pull requests to the `dependabot` user.
* Changed the label from `dependencies` to `No deployment` for Dependabot pull requests.

[TECH] Remove the pull request assignment to dependabot

---

.github/workflows/auto-merge.yml

This pull request includes significant changes to the `.github/workflows/auto-merge.yml` file, aimed at improving the auto-merge process by differentiating between standard pull requests and those created by Dependabot. The most important changes include renaming the auto-merge job, adding a new job specifically for Dependabot, and updating conditions for running these jobs.
Changes to auto-merge process:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L25-R27): Renamed the `auto_merge` job to `auto_merge_standard` and updated the condition to exclude Dependabot as the actor.
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243R51-R68): Added a new …

[TECH] Use the dependabots commands to merge

---

sample.env
src/App.vue
src/__tests__/acceptance/DownloadPageView.spec.js
src/__tests__/scripts/update_translation.spec.js
src/__tests__/vite.config.setup.test.js
vite.config.js
vite.config.setup.test.js
vitest.config.js

This pull request includes several changes to improve the environment configuration and testing setup. Key changes include the removal of unused environment variables, updates to the testing framework, and modifications to the environment variable handling in the codebase.
* Removed unused environment variables from `sample.env`.
* Updated environment variable handling in `src/App.vue` to use `import.meta.env.MODE` instead of `process.env.VUE_APP_ENVIRONMENT`.
* Removed `vite-plugin-env-compatible` and related environment variable definitions from `vite.config.js`. [[1]](diffhunk://#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26L7-R21) [[2]](diffhunk://#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26L40-L43)
* Modified `beforeEach` and …

[TECH] Using MODE environment variable

---

.github/workflows/auto-merge.yml

This pull request simplifies and consolidates the auto-merge workflow in the `.github/workflows/auto-merge.yml` file by merging the `auto_merge_standard` and `merge_dependabot` jobs into a single `auto_merge` job. The changes ensure that the correct token is used based on the actor.
Consolidation of auto-merge workflow:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L25-R33): Renamed `auto_merge_standard` job to `auto_merge` and removed the `merge_dependabot` job. Updated the token logic to use `DEPENDABOT_TOKEN` if the actor is `dependabot[bot]`, otherwise use `GH_TOKEN`. [[1]](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L25-R33) …

[REVERT] Revert the merge by dependabot

---

src/__tests__/scripts/send-log-message-script.spec.js
src/components/UploadFileComponent.vue
src/scripts/send-error-message-script.js
src/scripts/send-log-message-script.js
src/views/DownloadPageView.vue
src/views/FaqView.vue
vite.config.js
vitest.config.js

This pull request focuses on renaming and updating the `send-error-message-script.js` to `send-log-message-script.js`, modernizing environment variable usage, and refactoring configuration files. Below are the most important changes grouped by theme.
* Renamed `send-error-message-script.js` to `send-log-message-script.js` and updated all relevant imports across the codebase, including `UploadFileComponent.vue`, `DownloadPageView.vue`, and `FaqView.vue`. [[1]](diffhunk://#diff-c424b05fc57c2a26c59426902698a34f21e4c39d8316e05a709a3aa33e487fbfL1-R1) [[2]](diffhunk://#diff-bd9f944f416afa6444a3bf9b8f36a35b9ddb877861404829691e888487c57af5L2-R2) [[3]](diffhunk://#diff-611b70bedce12a6cbc6642e1de902ec1aca842de0f9222a98dd630165d90747cL2-R2) …

[TECH] Change the vite configuration

---

src/__tests__/settings.test.js
src/settings.json

This pull request removes the `id` field from all settings in the `src/settings.json` file and updates the corresponding test logic in `src/__tests__/settings.test.js` to reflect this change. The `id` field was deemed redundant and has been removed to simplify the settings structure.
* Removed the `id` field from all settings in `src/settings.json`, including settings under categories such as `system`, `bluetooth`, `editor`, `math`, `music_xml`, `music_bxml`, `speech`, `radio`, `agenda`, and `braille_learning`. This affects all setting types, including `menu`, `checkbox`, `number`, and `text`. [[1]](diffhunk://#diff-77439b31f09e0feb357768dec91579a7c7fdc37b2a417b92fd31aab5e5f3593bL4) [[2]](diffhunk://#diff-77439b31f09e0feb357768dec91579a7c7fdc37b2a417b92fd31aab5e5f3593bL14-L29) …

[TECH] Remove the unused id of settings file

---

src/scripts/add-new-setting.js

This pull request includes a minor change to the `AddNewSetting` class in the `src/scripts/add-new-setting.js` file. The `id` property has been removed from the object assigned to `section[this.key]`.
* [`src/scripts/add-new-setting.js`](diffhunk://#diff-9d0c7b36c2c3961cce7fb4ac366cf17f311f79d60eebd83662ae401dfc2152f1L127): Removed the `id` property from the object assigned to `section[this.key]` in the `AddNewSetting` class.

[TECH] Delete the script id field

---

src/__tests__/components/SettingComponent.spec.js
src/components/SettingComponent.vue

This pull request modifies the `SettingComponent` to replace the `number` input type with a `range` input type for better user experience. It also updates the corresponding test cases and adds a `datalist` for tick marks on the range input.
* Replaced the `number` input type with a `range` input type for settings of type `number`, ensuring a more user-friendly slider interface.
* Added a `datalist` element to provide tick marks for the `range` input, showing the minimum, default, and maximum values.
* Updated the `updateSetting` method to parse the `range` input value as an integer when the setting type is `number`.
* Updated the test case in `SettingComponent.spec.js` to validate the behavior of the `range` input type instead of the `number` input type.

[FEATURE] Use the range type for setting component

---

.github/workflows/ci.yml

This pull request updates the CI workflow configuration in `.github/workflows/ci.yml` to include support for `push` events and modifies conditional logic for the `vitest` job. These changes aim to enhance deployment flexibility and ensure tests are triggered appropriately.
Workflow configuration updates:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fR8-R10): Added support for `push` events to trigger workflows on the `main` branch.
Job condition adjustments:
* [`.github/workflows/ci.yml`](diffhunk://#diff-b803fcb7f17ed9235f1e5cb1fcd2f5d3b2838429d4368ae4c57ce4436577f03fL32-R35): Updated the conditional logic for the `vitest` job to allow execution for `push` events, while maintaining existing conditions for pull requests.

tech: check vitest on main branch

---

src/views/DownloadPageView.vue

This pull request includes a small update to the `DownloadPageView.vue` file, improving the conditional rendering of the download link for the last version.
* [`src/views/DownloadPageView.vue`](diffhunk://#diff-611b70bedce12a6cbc6642e1de902ec1aca842de0f9222a98dd630165d90747cL73-R77): Added a `v-if` condition to ensure the download link for the last version is only rendered if `last_version['file']` exists.

fix(app): display the link to download last version only if is available

---

.github/workflows/release.yml

This pull request simplifies the release workflow by removing unnecessary inputs and validation checks, and renaming the workflow file for clarity. The changes streamline the process of generating and pushing new versions.
Workflow simplification:
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L4-L12): Removed the `release_type` input and its validation logic, simplifying the workflow configuration. [[1]](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L4-L12) [[2]](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L22-L28)
* [`.github/workflows/release.yml`](diffhunk://#diff-87db21a973eed4fef5f32b267aa60fcee5cbdf03c67fafdc2a9b553bb0b15f34L54-R42): Updated …

tech(workflow): remove release_type from release workflow

---

README.md

This pull request includes a small update to the `README.md` file. The change updates the link to the contribution guide to point to the correct URL on GitHub.

docs: fix the readme link for goto contribution guide

---

eslint.config.mjs
src/components/LoadingSpinner.vue
src/components/NotificationToast.vue

This pull request introduces a new ESLint rule for Vue block order and reorganizes the structure of Vue component files by moving `<template>` sections below `<script>` sections to align with the new rule. The most important changes include the addition of the ESLint rule and the restructuring of the `LoadingSpinner` and `NotificationToast` components.
* Added the `"vue/block-order"` rule to enforce the order of blocks in Vue single-file components (`<script>`, `<template>`, `<style>`).
* Moved the `<template>` section below the `<script>` section in the `LoadingSpinner.vue` component to comply with the new block order rule. [[1]](diffhunk://#diff-0addca6bd97c644599546dc23f2f1b8dff03a96d23d1c582056a58de102cfa67L1-L7) [[2]](diffhunk://#diff-0addca6bd97c644599546dc23f2f1b8dff03a96d23d1c58205 …

tech(linter): Add linter rule for vue components

---

src/tests/components/FooterComponent.spec.js
src/tests/components/helpers.js

Today; the render include just the function t for legacy api. If using composition api, we must include manualy i18n in the tests.
Include i18n in render to migrate all vue components in composition api.
We can removing the i18n mock in the footer test
Check that all tests past.

tech: include i18n file in test render

---

.github/workflows/PR Title Check.yml

This pull request updates the GitHub Actions workflow configuration for pull request title checks to ensure the workflow triggers on more pull request events.
Workflow trigger improvements:
* [`.github/workflows/PR Title Check.yml`](diffhunk://#diff-e6d2be8389bd688a7879afcde237f873c599b6d1fe794a6a4352e4a428192e93L5-R5): The workflow is now triggered on `open`, `reopened`, and `synchronize` pull request events instead of just `opened`, ensuring title checks run in more scenarios.

fix(workflow): check title when pr is synchronised

---

src/App.vue

This pull request refactors the main `App.vue` component to use the `<script setup>` syntax and Vue 3 Composition API features, resulting in a more modern and concise codebase. The changes also update how localization and routing are handled, making the component more idiomatic for Vue 3 projects.
**Refactor to Composition API and `<script setup>`:**
* Converted the component from Options API to Composition API using `<script setup>`, replacing `data`, `methods`, and lifecycle hooks with `ref` variables and composition functions.
* Updated event handlers and reactive state (`mainRef`, `hasLanguage`, `canReset`) to use `ref` and standard functions instead of methods.
**Localization and routing improvements:**
* Replaced usage of `this.$i18n` and `this.$router` with direct imports of …

refactor: migrate the App file to composition api

---

src/components/NotificationToast.vue
src/tests/components/NotificationToast.spec.js
src/views/SettingsView.vue

This pull request introduces comprehensive unit tests for the `NotificationToast` component and includes minor improvements to prop referencing in both the component and its usage in `SettingsView`. The tests cover a range of behaviors, including rendering, auto-closing, dismissibility, and conditional display of elements.
**Testing improvements:**
* Added a complete test suite for `NotificationToast.vue`, covering rendering, auto-close behavior, dismissibility, and conditional title/close button display.
**Component and usage fixes:**
* Updated `NotificationToast.vue` to consistently reference the `title` prop as `props.title` for clarity and correctness.
* Fixed the notification list rendering in `SettingsView.vue` to use `notifications.notifications.value` for proper reactivity.

fix: Fix notification toast and setting view notification usage

---

index.html
package-lock.json
src/App.vue
src/components/NavBarComponent.vue
src/style.css

- Language selection page had poor readability (low contrast, faint labels).
- Missing global accessibility scaffolding (skip link, HTML `lang`, route change announcements).
- Keyboard navigation on the language screen was not fully accessible (no proper radio group).
- Global a11y scaffolding:
- Add skip link (“Skip to main content”).
- Sync `html[lang]` with the selected locale.
- Add `aria-live` region to announce route changes.
- Language selection redesign:
- Accessible form with `form` + `fieldset`/`legend` + radio inputs.
- Clickable cards via associated `<label>`; visible focus states.
- “Continue” button stays disabled until a language is selected.
- High-contrast styles for light and dark modes (cards, titles, codes, legend).
- Minor design polish (spacing, shadows, consistent …

feat(a11y): global scaffold (skip link, lang sync, route announcements) and accessible language selection UI with high-contrast styles

---

.github/workflows/PR Title Check.yml

This pull request makes a small update to the pull request title check workflow. The workflow now runs when a pull request is edited, instead of when it is synchronized.
* [`.github/workflows/PR Title Check.yml`](diffhunk://#diff-e6d2be8389bd688a7879afcde237f873c599b6d1fe794a6a4352e4a428192e93L5-R5): Changed the workflow trigger from `synchronize` to `edited` in the `types` list for pull request events.

fix(workflow): start pr title check when edited pull request
