src/router/router-list.js
src/views/DownloadPageView.vue

Il fallait une page de téléchargement
La mettre en place.

[FEATURE] Ajouter une page de téléchargement

---

src/router/index.js

Lorsqu'on changeait de page, l'élément title restait le même.
Mettre une actualisation dynamique.

[FEATURE] Changer le title des pages en fonction de la route

---

.github/pull_request_template.md

A partir de cette validation de PR, les pull requests auront un template à la création.

[FEATURE] Ajouter un template pour les pull requests

---

README.md

Le fichier [readme](https://github.com/theotime2005/bnote-settings/blob/621894ffded21954bb15042f7da81aa70c5d1542/README.md#L1-L0) n'était pas adapté au projet, il s'agissait du fichier de base.
Réécrire le fichier.

[FEATURE] Modifier le README pour l'adapter au projet

---

README.md

Il y a un serveur Discord mais il n'avait pas été mis dans le readme.
Le rajouter.

[BUGFIX] Ajouter le lien vers le serveur Discord

---

locales/en.json
locales/fr.json
locales/it.json
src/components/UploadFileComponent.vue
src/i18n.js
src/views/SettingsView.vue

L'Italien n'était pas supporté.
C'est désormais chose faite.

[FEATURE] Ajouter l'Italien et correction de clef de traduction

---

.github/workflows/check-tests.yml
.github/workflows/update-dependencies.yml

Il n'est pas possible de mettre les packages à jour de manière hebdomadaire à la main.
Mettre en place un workflow qui va s'en charger.
Les PR seront automatiquement merged si tous les tests sont passés.

[FEATURE] Ajouter une action pour mettre à jour les dépendances du projet chaque semaines

---

.github/workflows/update-dependencies.yml

L'action d'update des packages ne fonctionnait pas.
Corriger le problème

[FEATURE] Correction dans le script d'update de dépendances

---

src/views/SettingsView.vue

Il y a plusieurs section qu'on peut réduire/agrandir, mais on peut vite s'y perdre.
Fermer toutes les sections à l'appuie de la touche échappe.

[FEATURE] Fermer toutes les sections de la page paramètre à l'appuie de la touche échappe.

---

.github/workflows/update-dependencies.yml

L'action de mise à jour des paquets renvoyait des erreurs
Corriger.

[BUGFIX] Corriger l'action GitHub

---

.github/workflows/Update version on merge.yml
locales/en.json
locales/fr.json
locales/it.json
src/components/FooterComponent.vue

On a pas le numéro de version du projet lorqu'on va sur le site.
Importer le numéro de version depuis le package.json.

[FEATURE] Ajouter la version du projet dans le footer du site

---

.github/workflows/Update version on merge.yml
.github/workflows/update-dependencies.yml

[BUGFIX] Corriger les actions GitHub

---

.github/workflows/Update version on merge.yml
.github/workflows/check-lint.yml
.github/workflows/check-tests.yml
.github/workflows/update-dependencies.yml

C'est pas une belle PR, mais ça passera.

[BUGFIX] Correction dans les actions

---

.github/workflows/Update packages.yml
.github/workflows/Update version on merge.yml

Avec les workflows, on arrivait pas à faire de push sur la branche main. Fixes #26
Ajouter une permission et le token d'accès dans le checkout.

[BUGFIX] Corriger les actions une dernière fois

---

src/views/DownloadPageView.vue

The repository with the modified source code needs to be reorganized and the releases will no longer be available.
Remove the references in the page.
The code has just been commented and the functions preserved.

[FEATURE] Change the download page

---

.github/pull_request_template.md
locales/en.json
locales/fr.json
locales/it.json
public/faq/fr.json
src/components/SettingComponent.vue
src/router/router-list.js
src/views/FaqView.vue
src/views/HomeView.vue
src/views/SettingsView.vue

There was no FAQ page. It could be useful for informing users.
Add this page.
The FAQ page is not translated in the same way, there will be an FAQ for each language.
Go to the site and click on the FAQ tab.

[MAJORFEATURE] Create a FAQ page

---

public/faq/en.json
public/faq/fr.json

The FAQ wasn't translated in english.
Do the translation.

[MINORFEATURE] Add content into the FAQ and translate all FAQ in english

---

.github/issue_template/issue.yml

If we opened an exit on the deposit, we have no form.
Create the form respecting the .yml code.
There is no real way to test before application.
We can't test.

[MINORFEATURE] Add a template for issues

---

.github/workflows/Update version on merge.yml
.prettierrc.json
src/__tests__/components/LanguageComponent.spec.js
src/__tests__/components/UploadFileComponent.spec.js
src/__tests__/settings.test.js
src/components/LanguageComponent.vue
src/router/index.js
src/router/router-list.js

Pretierrc is installing but no use in to project.
Use `npm run formate` after merge a pull request.

[TECH] Use pretierrc to reformate code

---

src/__tests__/components/LanguageComponent.spec.js
src/__tests__/components/UploadFileComponent.spec.js
src/__tests__/settings.test.js
src/components/LanguageComponent.vue
src/router/index.js
src/router/router-list.js

If the page was reloaded, the display language was no longer kept and there was no way to save it.
Put the language in the URL and process it at the time of rendering.
- Launch the project and go to a page,
- Note that the language is present in the URL,
- Change language,
- See the change in the url.

[MINORFEATURE] Add the language in the URL

---

src/__tests__/components/LanguageComponent.spec.js
src/__tests__/components/UploadFileComponent.spec.js
src/__tests__/settings.test.js
src/components/LanguageComponent.vue
src/router/index.js
src/router/router-list.js

The #48 was merged but not end.

[MINORFEATURE] Set language in route n°2

---

src/__tests__/components/LanguageComponent.spec.js
src/components/LanguageComponent.vue
src/router/index.js
src/router/router-list.js

When we try to reload the page, we have an error that is currently complicated to correct.
Remove (for now) the language in the URL.
Maybe to be put back later?

[BUGFIX] Remove the language from the URL

---

locales/en.json
locales/fr.json
locales/it.json
src/__tests__/components/SettingComponent.spec.js
src/components/SettingComponent.vue

There was no button to reset the default value for each setting.
Include a button that is only displayed if the value is not the default one.
Is it necessary for all settings?

[MINORFEATURE] Add a button to reset the default value

---

.github/workflows/codeql.yml

This pull request introduces a new GitHub Actions workflow for CodeQL analysis, which is designed to enhance code security and quality by automatically scanning the codebase for vulnerabilities and errors. The workflow is configured to run on pushes and pull requests to the main branch, as well as on a scheduled basis.
Key changes include:
* Added a new workflow file `.github/workflows/codeql.yml` to set up CodeQL analysis for the repository. This includes defining the workflow name, triggers (push, pull_request, schedule), and job configuration.
* Configured the job to run on different operating systems based on the language being analyzed, with support for languages like JavaScript, TypeScript, and others.
* Included steps to checkout the repository, initialize CodeQL, and perform the …

[TECH] Create codeql.yml

---

.github/workflows/Update packages.yml
.github/workflows/Update version on merge.yml

- **fix: Check that tests past and change action name**
- **change action name**
In the workflow to update packages, there is no verification to check that all packages is also compatible.
Add a line to run tests. Any more, change name of github username to distinct packages updater and version updater.

[TECH] Corrrections in workflo

---

.github/workflows/Build version.yml

Ther's not solution to build automatically a new version
Create a workflow to build a new version with a shell script.

[TECH] Add a workflow to build version

---

.github/workflows/Merge into production.yml
.github/workflows/build-version.yml

This pull request includes changes to the GitHub Actions workflows to improve security and consistency. The most important changes include adding a token for authentication and renaming a workflow file for consistency.
Improvements to GitHub Actions workflows:
* [`.github/workflows/Merge into production.yml`](diffhunk://#diff-feb6c932862b240e3d403ca1f283ee039e8ed7e026c832947bf431f4bc37d178R19): Added `token: ${{ secrets.GH_TOKEN }}` to the `Checkout code` step to improve security.
* [`.github/workflows/Build version.yml`](diffhunk://#diff-c8e0932e362c6cf2133d2797ec3edf7699d897d626a9f35f5e156ddc27636516L4-R4): Renamed the file to `build-version.yml` for consistency and added `token: ${{ secrets.GH_TOKEN }}` to the `Checkout repository` step. …

[TECH] Add the token element in the workflow checkout with push

---

.gitignore
package-lock.json
package.json
sample.env
vite.config.js

This pull request includes updates to the `package.json` and `vite.config.js` files to add a new plugin and improve environment variable compatibility.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R22): Added the `vite-plugin-env-compatible` dependency to ensure compatibility with environment variables.
Configuration updates:
* [`vite.config.js`](diffhunk://#diff-58e6f63d87181b1c6a8cb6e5f1691df04aa32854456efcd52ca71c8541375d26L2-R24): Imported and configured the `vite-plugin-env-compatible` plugin. Added environment variable loading and defining `__APP_ENV__` to the Vite configuration.

[TECH] Configure the project to use environment variables

---

.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

This pull request includes significant updates to the GitHub Actions workflows for linting and testing. The changes aim to improve error detection and reporting for both ESLint and test runs by adding steps to check outputs and comment on pull requests when errors or failures are detected.
Improvements to ESLint workflow:
* [`.github/workflows/check-lint.yml`](diffhunk://#diff-20fe1266f89be6c7574eb75d9d5f94a20068c4d38bc7ea1900074a6a69f7a917R13-R14): Added permissions to allow commenting on pull requests, modified the ESLint step to capture output and set environment variables, added a step to check for ESLint errors, and added a step to comment on the pull request if errors are detected. [[1]](diffhunk://#diff-20fe1266f89be6c7574eb75d9d5f94a20068c4d38bc7ea1900074a6a69f7a917R13-R14) …

[TECH] Return the results of the CI in the pull request comments

---

.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

…l-request"
This reverts commit 9d07dd20c41dbbcaab92e588368b8cf4fefa72ec, reversing changes made to 71d302148ab87d08a2a146d56356bf89b21532b1.

[TECH] Revert the CI update

---

sample.env
src/__tests__/scripts/send-error-message-script.spec.js
src/components/UploadFileComponent.vue
src/scripts/send-error-message-script.js
src/views/DownloadPageView.vue
src/views/FaqView.vue
vite.config.setup.test.js
vitest.config.js

This pull request includes several changes to improve error logging and environment variable usage throughout the project. The most important changes include updating environment variable names, integrating the `sendLog` function for error handling, and modifying test configurations.
* Updated environment variable names to follow the `VUE_APP` prefix convention in `sample.env` and `src/__tests__/scripts/send-error-message-script.spec.js`. [[1]](diffhunk://#diff-b80385df109d2e96812772e7905b6d846a851623b7261d35480bdb4e83a009d0R2-R7) [[2]](diffhunk://#diff-b499a35efbc89039a40fad5dfd83783d58fa65633f38c4435ef0b03d0c1e4659L8-R8) [[3]](diffhunk://#diff-b499a35efbc89039a40fad5dfd83783d58fa65633f38c4435ef0b03d0c1e4659L62-R62) [[4]](diffhunk://#diff-b499a35efbc89039a40fad5dfd83783d58fa65633f38c4435e …

[FEATURE] Migrate console errors to the new send to API function

---

package-lock.json
package.json
src/__tests__/components/NaveBarreComponent.spec.js
src/__tests__/components/UploadFileComponent.spec.js
src/components/FooterComponent.vue
src/components/LanguageComponent.vue
src/components/NaveBarreComponent.vue
src/components/UploadFileComponent.vue
src/main.js
src/router/index.js
src/router/router-list.js
src/stores/counter.js
src/style.css
src/views/DownloadPageView.vue
src/views/FaqView.vue
src/views/HomeView.vue
src/views/SettingsView.vue

This pull request includes various changes focused on improving code consistency, adding new functionality, and updating tests. The most important changes include adding a new store for counter functionality, improving the consistency of template syntax, and updating tests to handle edge cases.
* Updated template syntax across multiple Vue component files to use consistent spacing and formatting for better readability. (`src/components/FooterComponent.vue`, `src/components/LanguageComponent.vue`, `src/components/NaveBarreComponent.vue`, `src/components/UploadFileComponent.vue`, `src/views/FaqView.vue`, `src/views/HomeView.vue`, `src/views/SettingsView.vue`) [[1]](diffhunk://#diff-7490b18034c0e87a348ce68c97884563c04d5fbe2ff5f42a85dc927ff0ce5f94L16-R31) …

[TECH] Clean the commits that were no longer useful

---

package-lock.json

This pull request is a simple package update.

[BUMP] Update dependencies

---

package.json

This pull request includes changes to the `package.json` file to configure `standard-version` with custom release types and sections. This enhancement will help categorize changes more effectively in the changelog.
Configuration of `standard-version`:
* Added a `standard-version` configuration to the `package.json` file, which includes custom types and sections for categorizing changes such as "Features", "Bug Fixes", "Chores", "Documentation", "Styles", "Refactors", "Performance", "Tests", "Technical Tasks", and "Version Bumps".

[TECH] Add new informations for changelog

---

.github/dependabot.yml
.github/semantic.yml

This pull request introduces configuration files for Dependabot and semantic PR validation. The changes ensure that dependencies are kept up-to-date and that PR titles and commits adhere to semantic versioning guidelines.
Configuration updates:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R32): Added configuration to fetch and update the latest `npm` and `github-actions` packages daily, with specific reviewers and assignees.
* [`.github/semantic.yml`](diffhunk://#diff-d0fba0e4da9ee5243a62a1d784a394b72ad0d60b8c866fa7c9a8a572ded87888R1-R5): Added configuration to validate PR titles and all commits, and allow merge commits.

[TECH] Custom dependabot alert

---

.github/dependabot.yml

This pull request includes changes to the `.github/dependabot.yml` file to improve the configuration for dependency updates. The most important changes include modifying the labels section and adding a new configuration block for `github-actions` packages.
Configuration improvements:
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28L10-R10): Changed the indentation of the `labels` section under `updates:` to ensure proper YAML formatting.
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R21): Added a new configuration block to fetch and update the latest `github-actions` packages.

[BUGFIX] Correct the dependabot file

---

.github/workflows/enable auto merge.yml

This pull request includes the addition of a new GitHub Actions workflow to enable auto merge for pull requests labeled "Ready to merge".
New GitHub Actions workflow:
* [`.github/workflows/enable auto merge.yml`](diffhunk://#diff-39a04bab1c94543645918dfaeae11f004c72e1c6546ac2ad9a1d000aba25d5a9R1-R24): Added a workflow that triggers on pull requests to the `main` branch and enables auto merge if the pull request has the "Ready to merge" label.

[FEATURE] Add a workflow to enable automatic merge

---

.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

This pull request includes small changes to the GitHub Actions workflows for ESLint and tests. The changes ensure that the workflows are triggered on `synchronize` events for pull requests.
* [`.github/workflows/check-lint.yml`](diffhunk://#diff-20fe1266f89be6c7574eb75d9d5f94a20068c4d38bc7ea1900074a6a69f7a917R5-R6): Added `synchronize` to the `types` under `pull_request` to trigger the ESLint check on synchronization events.
* [`.github/workflows/check-tests.yml`](diffhunk://#diff-e6ca5345641700b84db3333c2e2038a963319137c37cf92fa6c3e214ccb8ede3R5-R6): Added `synchronize` to the `types` under `pull_request` to trigger the test check on synchronization events.

[TECH] Relaunch the IC when the status of the pr changes

---

.github/workflows/check-lint.yml
.github/workflows/check-tests.yml

This pull request includes updates to the GitHub Actions workflows to trigger additional events.
Changes to GitHub Actions workflows:
* [`.github/workflows/check-lint.yml`](diffhunk://#diff-20fe1266f89be6c7574eb75d9d5f94a20068c4d38bc7ea1900074a6a69f7a917R7): Added the `opened` event type to the `pull_request` trigger.
* [`.github/workflows/check-tests.yml`](diffhunk://#diff-e6ca5345641700b84db3333c2e2038a963319137c37cf92fa6c3e214ccb8ede3R7): Added the `opened` event type to the `pull_request` trigger.

[TECH] Start the CI when open a pull request

---

package-lock.json
package.json
postcss.config.js
src/App.vue
src/style.css
src/views/SettingsView.vue
tailwind.config.js
vite.config.js

Reverts theotime2005/bnote-settings#135

Revert "[BUGFIX] Repare tailwindcss"

---

package-lock.json
package.json

Reverts theotime2005/bnote-settings#117

Revert "[BUMP](deps-dev): Bump tailwindcss from 4.0.5 to 4.0.6"

---

.github/workflows/auto-merge.yml

a## Problem
The workflow did not waiting the end of check status to merge.
Move the check_suite condition.

[TECH] Wait success status to merge

---

.github/workflows/auto-merge.yml

Reverts theotime2005/bnote-settings#145

[TECH] Revert  Testing the auto merge configuration

---

.github/workflows/auto-merge.yml

This pull request includes significant changes to the GitHub Actions workflows by removing the auto-merge workflow and adding a new merge queue workflow.
Changes to GitHub Actions workflows:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L1-L65): Removed the entire auto-merge workflow, which included steps for checking out the repository, rebasing branches, and merging pull requests based on specific conditions.
* [`.github/workflows/merge-que.yml`](diffhunk://#diff-db889391b85ec12bf7032b74de3bf6ed9d368d379a27cbb57a5dfb8582101d22R1-R40): Added a new merge queue workflow that includes steps for checking out the repository, setting up Node.js, installing dependencies, running tests, and adding pull requests to a merge …

[TECH] Change the merge configuration

---

.github/workflows/auto-merge.yml

This pull request includes several changes to the `.github/workflows/auto-merge.yml` file to streamline the auto-merge process and improve the workflow's efficiency. The most important changes involve updating the configuration for user details and simplifying the merge process by removing unnecessary steps.
Workflow improvements:
* Updated the user details for the git configuration to use "auto merge service" instead of "github-actions[bot]" (`.github/workflows/auto-merge.yml`).
* Removed the rebase step and associated checks, simplifying the workflow by eliminating the need to handle rebase failures (`.github/workflows/auto-merge.yml`).
* Consolidated the steps for enabling auto-merge or merging the pull request into a single step, removing the need for intermediate checks and …

[TECH] Remove lecacy code form auto merge workflow

---

sample.env

We will finally not move on to the API composition. The feature toggle is therefore useless.
Remove the feature toggle.

[TECH] Remove the feature toggle for the API composition

---

src/App.vue
src/__tests__/scripts/useLocaleCookie.spec.js
src/router/index.js
src/scripts/useLocaleCookie.js
vite.config.js
vitest.config.js

This pull request includes several changes to improve locale handling, add a new feature for resetting cookies, and update the environment configuration. The most important changes include refactoring the `App.vue` script setup, adding a method to remove locale cookies, updating the router to handle locale cookies, and modifying the environment configuration files.
* [`src/App.vue`](diffhunk://#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0L1-R74): Refactored the script setup to use the options API, added methods for setting locale and resetting cookies, and updated the template to conditionally render content based on the presence of a locale.
* [`src/scripts/useLocaleCookie.js`](diffhunk://#diff-10616058f7dae80babc68c2d2ea609c617d92e44a7c134b955f2627a5acf27a6R11-R1 …

[FEATURE] Put a page with the different languages proposed before displaying the site

---

.prettierrc.json
eslint.config.mjs
package.json
src/App.vue
src/__tests__/acceptance/HomeView.spec.js
src/__tests__/acceptance/SettingsView.spec.js
src/__tests__/scripts/send-error-message-script.spec.js
src/__tests__/settings.test.js
src/scripts/send-error-message-script.js
src/scripts/update_translation.js
src/stores/settingsStore.js
src/views/SettingsView.vue
vite.config.js
vitest.config.js

This pull request includes several updates to the codebase, primarily focusing on the ESLint configuration, code style improvements, and minor refactoring for consistency. The most important changes are grouped by theme as follows:
* Updated `eslint.config.mjs` to import necessary plugins and configurations, and removed the unused `eslint-plugin-import`. [[1]](diffhunk://#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2L1-R37) [[2]](diffhunk://#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2L54-R88) [[3]](diffhunk://#diff-9601a8f6c734c2001be34a2361f76946d19a39a709b5e8c624a2a5a0aade05f2L93-R100)
* Removed `eslint-plugin-import` from `package.json` dependencies.
* Replaced `let` with `const` for loop variables in various files to ensure …

[TECH] Custom the linting

---

package.json

Reverts theotime2005/bnote-settings#152

[TECH] Revert the pr that remove scopes of standard-version

---

Contribution guide.md
README.md
docs/bnote settings systems.md

This pull request includes updates to the documentation and addition of new sections to improve clarity and provide more information for contributors and users. The most important changes include fixing a typo in the contribution guide, adding new sections to the README, and creating a detailed document for B.note settings.
Documentation improvements:
* [`Contribution guide.md`](diffhunk://#diff-82179c14266153a0a951268d0eb1d1a95aaed510427f3bdf209231addcc91a05L21-R21): Fixed a typo in the documentation scope description.
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R54-R59): Added sections for contributing and joining the Discord server to discuss the project and receive notifications.
* [`docs/bnote settings …

[DOCS] Documentation for the repository

---

package.json

This pull request includes updates to the workflow configuration, documentation, and package metadata. The most important changes are detailed below:
* [`.github/workflows/auto-merge.yml`](diffhunk://#diff-9e68ee04621d1e0e7dd2bf6032197d7a7848afb1a5c4ad805f617b330165e243L11-R11): Modified the `on:` section to replace `check_suite` with `ready_for_review`.
* [`CHANGELOG.md`](diffhunk://#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR5-R13): Added entries for version 2.1.2, including new documentation updates and fixes.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L3-R3): Updated version from 2.1.1 to 2.1.2.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L22-R54): …

[TECH] Revert a not correct pr 

---

.github/workflows/auto-merge.yml
package.json

In the types of commits to be included in the new versions we had all the commits. However, we only want the main ones with the pull requests.
- Add the right scopes to the package.json,
- Modify the auto merge workflow so that it uses the title of the pr as a commit.

[TECH] Customize the changelog and correct the auto merge workflow

---

.gitignore
package-lock.json

We realize that the package-lock.json file is still practical.
Remove the file from the .gitignore.

[BUGFIX] added package-lock

---

.releaserc.json
package-lock.json
package.json

This pull request includes updates to the release configuration and dependencies in the project. The most important changes are the removal of redundant commas in the release configuration file and the addition of new dependencies in the `package.json` file.
Release configuration updates:
* [`.releaserc.json`](diffhunk://#diff-e774e90e159e39c0a392fffa584ea8520508a9a0c10468d0bd685800e28a42f5L17-R22): Removed redundant commas from the array of release rules.
Dependency updates:
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R21): Added `@theotime2005/conventional-changelog` to dependencies.
* [`package.json`](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R34-R36): Added `@semantic-release/changelog`, …

[BUGFIX] Fix the file for semantic release

---

eslint.config.mjs
src/__tests__/acceptance/DownloadPageView.spec.js
src/__tests__/acceptance/HomeView.spec.js
src/__tests__/acceptance/SettingsView.spec.js
src/__tests__/components/helpers.js
src/__tests__/scripts/send-error-message-script.spec.js
src/__tests__/scripts/update_translation.spec.js
src/__tests__/vite.config.setup.test.js

This pull request includes several changes to improve code consistency and readability, particularly in test files. The most important changes involve converting function expressions to arrow functions in various test files and updating function declarations for better clarity.
Code consistency improvements:
* [`src/__tests__/acceptance/DownloadPageView.spec.js`](diffhunk://#diff-edc27cec1e7ae0287148790cc8dbb1d67820b946399062a601b509e20947a1e7L4-R4): Converted `beforeEach` function expression to an arrow function.
* [`src/__tests__/acceptance/HomeView.spec.js`](diffhunk://#diff-20f285aa098eefbaaa086c0c6caf9668f33495e5ff7f77159da5bdd56c52dd93L5-R5): Converted `beforeEach` function expression to an arrow function.
* [`src/__tests__/acceptance/SettingsView.spec.js`](diffhunk://#diff-405bbe0c4 …

[TECH] Refactor code base with function syntaxe

---

.github/workflows/ci.yml
README.md
package-lock.json
package.json
src/App.vue
src/components/FooterComponent.vue
src/components/LanguageComponent.vue
src/components/NavBarComponent.vue
src/components/SettingComponent.vue
src/components/UploadFileComponent.vue
src/style.css
src/views/AboutView.vue
src/views/DownloadPageView.vue
src/views/FaqView.vue
src/views/HomeView.vue
src/views/SettingsView.vue
vite.config.js

This pull request introduces significant updates to the codebase, focusing on the removal of Tailwind CSS, the adoption of custom CSS styles, and the enhancement of component structure and design. The changes aim to improve maintainability, readability, and consistency across the application.
* Removed `tailwindcss` and `@tailwindcss/vite` dependencies from `package.json` to transition away from Tailwind CSS. (`package.json`, [package.jsonL20-L24](diffhunk://#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519L20-L24))
* Replaced Tailwind CSS utility classes with custom CSS variables and styles in `src/style.css`, introducing a palette of colors, typography settings, spacing, and reusable components like buttons, containers, and cards. (`src/style.css`, …

[Feature] Remove any use of Tailwindcss in the project

---

.github/dependabot.yml
.github/workflows/PR Title Check.yml
.github/workflows/auto-merge.yml
Contribution guide.md

This pull request updates the repository's conventions for pull request titles and dependency updates, aligns workflows with the new conventions, and updates the contribution guide to reflect these changes. The most important changes include modifying title validation patterns, updating the prefix for dependency updates, adjusting the auto-merge workflow, and revising the contribution guide.
* [`.github/workflows/PR Title Check.yml`](diffhunk://#diff-e6d2be8389bd688a7879afcde237f873c599b6d1fe794a6a4352e4a428192e93L19-R19): Changed the validation pattern for pull request titles to use lowercase prefixes with a colon (e.g., `fix:`, `feat:`) instead of uppercase prefixes in square brackets (e.g., `[BUGFIX]`, `[FEATURE]`).
* [`.github/dependabot.yml`](diffhunk://#diff-dd4fbda47e51f1e35defb9275 …

tech: Update the development method

---

eslint.config.mjs
src/App.vue
src/components/LanguageComponent.vue
src/components/NavBarComponent.vue
src/components/SettingComponent.vue
src/components/UploadFileComponent.vue
src/views/DownloadPageView.vue
src/views/FaqView.vue
src/views/SettingsView.vue

This pull request includes several updates across multiple files, focusing on improving code maintainability, ensuring consistency, and adding new functionality. Key changes include reordering imports, refactoring lifecycle hooks, improving event handling, and enhancing component templates for better readability and functionality.
* **Reordered imports in `eslint.config.mjs`**: Simplified configuration by removing unused properties and ensuring compatibility with plugins like `i18n-json`.
* **`src/App.vue`**: Refactored the `beforeMount` lifecycle hook to improve maintainability and readability. The hook was removed and re-added with minor updates. [[1]](diffhunk://#diff-7a7a37b12ee1265d7e27577ec286120d2cbc0940908635e264a2be44ccb9a8a0R19-R33) …

refactor: fix the linter and lint views

---

.github/copilot-instructions.md

If using copilot to resolves some issues, it's important to put rules and informations for IA.
Write some instructions for copilot.
The document will be update with new instructions in the future.

docs: add instructions for processing issues and creating pull requests
